### ISSUE TITLE
Where has the code gone?

### ISSUE THREAD

**Issue by Jamie-** [jshea2/OSC-for-OBS#11]
Hey, I love your project. I've found it very useful and hacked it about to do various other things too. I came to the repo to fork it so I can give some of my modifications back to the community but all the code has been purged from the repo, how come?

It's a shame as this is a really great project!

**Comment by Jamie-** [comment]
Hey, thanks for updating. That would be great when you have some time. We all do this stuff in our spare time so no pressure but it would be great it you could do that :clap:

**Comment by cvazwm** [comment]
I also sign up! 
I look forward to it, it is an excellent project!
Thank you 👏👏

**Comment by jshea2** [comment]
Finally got the code on there! I apologize for how long this took me to do.
