### ISSUE TITLE
Problem Installing on Windows 10

### ISSUE THREAD

**Issue by randallpacker** [jshea2/OSC-for-OBS#19]
I am experiencing error issues when quitting OSC to OBS on Windows 10. There aren't any installation instructors for Windows, but here is how I have installed:

-- download to the downloads folder
-- drag the OSC-for-OBS-win32--ia32 folder to C: Program Files
-- launch OSC-for-OBS.exe

Everything seems to be working, however:
when I quit OSC to OBS I get this error message:

**A Javascript error occurred in the main process
Uncaught exception:
Error: EPERM operation not permitted, open 'C\Program Files\OSC-for-OBS-win32--ia32\resources\app\src\default.txt**

When I relaunch the applications all the settings are lost though I have saved a configuration file. 

I suspect that the Program Files folder is not the right place for the application, but I have no idea where else to put it!?

Thanks for your help @jshea2 

Randall

**Comment by randallpacker** [comment]
Problem Solved for Windows installation: 

Do not put OSC for OBS in the C:/Program Files folder
Create a new folder in the C root such as C:/Programs

Voila, the app now quits and saves without the above error message. 
@jshea2 I suggest putting these Windows installation instructions in the help. 

Many thanks... great software!!

**Comment by jshea2** [comment]
Thanks for this! I added it to the 'Setup' in the ReadMe.md

**Comment by randallpacker** [comment]
My pleasure Joe! Truly mind-blowing software that has changed the way I am using OBS in my media studio. 

 

All the best, 

 

Randall

 

 

3SN : : : Third Space Network

Internet Broadcast Channel for the Arts

Randall Packer, Creative Director

***@***.***

202-439-4306 (cel)

Website: http://www.thirdspacenetwork.com

 

Host of The Post Reality Show

https://www.postrealityshow.com/

November 12,19,26, December 3 ::: 2-4pm ET-US

 

 

 

From: Joe Shea ***@***.***>
Reply-To: jshea2/OSC-for-OBS ***@***.***>
Date: Saturday, October 22, 2022 at 1:26 PM
To: jshea2/OSC-for-OBS ***@***.***>
Cc: RANDALL PACKER ***@***.***>, Author ***@***.***>
Subject: Re: [jshea2/OSC-for-OBS] Problem Installing on Windows 10 (Issue #19)

 

Closed #19 as completed.
