### ISSUE TITLE
Way to reverse osc output string?

### ISSUE THREAD

**Issue by avidteacher** [jshea2/OSC-for-OBS#8]
Right now, the osc output puts the scene name in the middle of the osc address.   Is it possible to have it deliver the cue name as the osc data instead?   That way, I could use Isadora to evaluate the osc data and do something based on the cue name.  

Or any chance of getting an osc output source for obs?

**Comment by jshea2** [comment]
Hey, sorry just now seeing this. Would you want an output kinda like this: `/activeScene [scene-name]`?

Join the Discord server. I'm much more responsive there: https://discord.gg/FJ79AKPgSk

**Comment by avidteacher** [comment]
Yes, that is exactly what I would like to do - the Scene Name becomes a text string payload for osc.   It can then be evaluated by the name for further action in another program (i.e. if the name begins with "MAIN", lift the shutter on the main projector from Isadora)

**Comment by jshea2** [comment]
Try the new  [2.6.2](https://github.com/jshea2/OSC-for-OBS/releases/tag/2.6.2) update I added two new features for your issue. One is for when the transition is initiated and the other is when the transition is complete it'll send the OSC string of the name of the active scene
