### ISSUE TITLE
[Feature request] Send stream status via OSC output

### ISSUE THREAD

**Issue by jeremiasmanninen** [jshea2/OSC-for-OBS#9]
I'm using touchosc and I would be very pleased if it were possible to send stream status to OSC output. Eg. using toggle stream sending 0 or 1 or sending /startStreaming when the stream is on and /stopStreaming when it is off. 

Thank you for your AWESOME work!!!! 👍 😄

**Comment by jeremiasmanninen** [comment]
If using the latter better to change /startStreaming to /StreamingOn and /stopStreaming to /StreamingOff. 

Just an idea. 😄

**Comment by jshea2** [comment]
Great idea! It seems TouchOSC is becoming the popular use for the app. I'll add in some more toggle commands. Also, the naming scheme is mainly from how the API names them.

**Comment by jeremiasmanninen** [comment]
Thank you very much!

I'm also using multi-RTMP-plugin (https://obsproject.com/forum/resources/multiple-rtmp-outputs-plugin.964/) and thinking that would there be any possibilities to control the additional stream by OSC. I guess the controls would at first have to be in the WebSocket API. 

If you want to get more ideas for those touchosc toggle commands here is few I got by reading the websocket Api:

- A slider for obs audio in touchosc by sending the volume: (https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getvolume)
- OBS exist (https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#exiting) or same way to get status that that obs, obs websocket and osc for obs are running correctly. I would use it as a led in touchosc (led is on while getting 1 and of while getting 0)
- Send audio status (https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getaudioactive) or other stream status (CPU, fps...)
- Stream(and maybe rec timecode) sending. Can be used in touchosc label. https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getstreamingstatus

Hope those will fire you up! 😄

**Comment by jshea2** [comment]
I got most of the requests! The only one that wasn't available is 'exist' because 'heartbeat' is deprecated in obs-ws 4.9. I also added a lot more than requested. Try them out! TouchOSC File is updated as well 👍

**Comment by jeremiasmanninen** [comment]
Awesome! Il try out! Thanks a lot for so fast release time. 😄

**Comment by jeremiasmanninen** [comment]
I got a few other things that would help me and improve the app. 😄 

1. I use Touchosc LEDs for viewing the status of ATEM and other kinds of statuses too. It would be great to get /streaming to send 1 or 0 too, so the stream can be view also by led.
2. As sending scene status to TouchOSC it would be great to send the source visibility the same way.
3. Feedback from transition: showing current transition type and duration and when transition is going. 
4. I also thought of getting feedback from media controllers, eg. mediasource playing send (/MediaPlaying 1) and when stopped (/MediaPlaying 0).

I'm using an old original ATEM television studio that does not support video files and trying to build my own kind of video mixer layout with touchosc. Just wanted to tell how I use it. 

Best regards,
Jeremias Manninen, from Finland

**Comment by jshea2** [comment]
Hey! Sorry I didn't really notice this until now. I'm much more responsive on Discord: https://discord.gg/FJ79AKPgSk

Also, I'll take a look into these, most of them seem doable

**Comment by jshea2** [comment]
Had some time to code these. Try this new update out! https://github.com/jshea2/OSC-for-OBS/releases/tag/2.6.1

**Comment by jeremiasmanninen** [comment]
Thank you very much again!

ma 3. toukok. 2021 klo 2.19 Joe Shea ***@***.***> kirjoitti:
